### ISSUE TITLE
New Member: Neil Klingensmith

### ISSUE THREAD

**Issue by neilklingensmith** [LoyolaChicagoCS/ssl#16]
**Your Name:**
Neil Klingensmith

**Your Bio:**
I'm a new professor at Loyola Computer Science, and I'm mostly interested in embedded, IoT, and mobile computing. I just got my PhD from Wisconsin working on building automation systems. Favorite Star Trek character: Mr. Scott.

**Your GitHub Profie:**
https://github.com/neilklingensmith

**Personal Web Site:**
http://neilklingensmith.com

**Other Social Handles:**
- 
- 
-

**Comment by gkthiruvathukal** [comment]
@neilklingensmith So glad you are joining us!

**Comment by morganrmarie** [comment]
Updated!
