### ISSUE TITLE
New Research Project: Hermes

### ISSUE THREAD

**Issue by neilklingensmith** [LoyolaChicagoCS/ssl#17]
**Project Name**
Hermes

**Project Website**
http://hermes.cs.luc.edu

**Concise Project Description**
In this project, we're building virtualization tools for mobile and IoT systems. Think of it like [VMWare](https://www.vmware.com/) for your phone. Apps can run inside isolated virtual machines so they can't snoop your personal data, and the virtualization software can be installed by anyone---you don't need to root your phone for Hermes to work.

**Papers**

[Using Virtualized Task Isolation to Improve Responsiveness in Mobile and IoT Software](http://neilklingensmith.com/assets/papers/hermes-full.pdf)
Neil Klingensmith, Suman Banerjee
ACM IoTDI, Montreal, QC, CA, April 2019

[A Hypervisor-Based Privacy Agent for Mobile and IoT Systems](http://neilklingensmith.com/assets/papers/privagent.pdf)
Neil Klingensmith, Suman Banerjee
ACM HotMobile, Santa Cruz, CA, February 2019

[Hermes: A Real Time Hypervisor for Mobile and IoT Systems](http://neilklingensmith.com/assets/papers/p101-klingensmith.pdf)
Neil Klingensmith, Suman Banerjee
ACM HotMobile, Tempe, AZ, February 2018

**Comment by gkthiruvathukal** [comment]
@neilklingensmith Thanks for this submission. It is in the perfect format. I just created a new project template based on yours! 

@morganrmarie If you can get this linked onto the SSL pages, that would be great!
