### ISSUE TITLE
New Member: David B. Wetzel

### ISSUE THREAD

**Issue by gkthiruvathukal** [LoyolaChicagoCS/ssl#18]
**Your Name:**
David B. Wetzel

**Photo:**
![dbw](https://user-images.githubusercontent.com/651504/61808693-8456eb80-ae01-11e9-90b3-e5af6751373d.jpg)

**Your Bio:**

**Your GitHub Profie:**
https://github.com/[your id]

**LinkedIn:**
https://linkedin.com/in/[your id]

**Twitter:**
https://twitter.com/[your id]

**Personal Web Site:**
davidbrookewetzel.net

**Other Social Handles:**
- 
- 
-

**Comment by morganrmarie** [comment]
Updated 🎉
